################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
BSP/Src \
Core/Src \
Core/Startup \
Core/ThreadSafety \
Drivers/BSP/MX25L3233F \
Drivers/BSP/RX8900SA \
Drivers/STM32L4xx_HAL_Driver/Src \
EC_code/Src \
FATFS/App \
FATFS/Target \
Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/LittleFs \
TouchGFX/App \
TouchGFX/target \
TouchGFX/target/generated \
TouchGFX_App/build/MINGW32_NT-6.2/gui/src/menu2_screen \
TouchGFX_App/build/MINGW32_NT-6.2/gui/src/menu4_screen \
TouchGFX_App/generated/fonts/src \
TouchGFX_App/generated/gui_generated/src/common \
TouchGFX_App/generated/gui_generated/src/containers \
TouchGFX_App/generated/gui_generated/src/diagnostic_screen \
TouchGFX_App/generated/gui_generated/src/menulayer1_screen \
TouchGFX_App/generated/gui_generated/src/menulayer2_screen \
TouchGFX_App/generated/gui_generated/src/menulayer3_screen \
TouchGFX_App/generated/gui_generated/src/passwordentry_screen \
TouchGFX_App/generated/gui_generated/src/screenlcdtest_screen \
TouchGFX_App/generated/gui_generated/src/screenoutputstest_screen \
TouchGFX_App/generated/gui_generated/src/screentesthome_screen \
TouchGFX_App/generated/gui_generated/src/screentrailer_screen \
TouchGFX_App/generated/images/src \
TouchGFX_App/generated/images/src/__generated \
TouchGFX_App/generated/texts/src \
TouchGFX_App/gui/src/common \
TouchGFX_App/gui/src/containers \
TouchGFX_App/gui/src/diagnostic_screen \
TouchGFX_App/gui/src/menulayer1_screen \
TouchGFX_App/gui/src/menulayer2_screen \
TouchGFX_App/gui/src/menulayer3_screen \
TouchGFX_App/gui/src/model \
TouchGFX_App/gui/src/passwordentry_screen \
TouchGFX_App/gui/src/screenlcdtest_screen \
TouchGFX_App/gui/src/screenoutputstest_screen \
TouchGFX_App/gui/src/screentesthome_screen \
TouchGFX_App/gui/src/screentrailer_screen \
TouchGFX_App/touchgfx/framework/source/touchgfx/containers \
TouchGFX_App/touchgfx/framework/source/touchgfx/containers/clock \
TouchGFX_App/touchgfx/framework/source/touchgfx/containers/progress_indicators \
TouchGFX_App/touchgfx/framework/source/touchgfx/containers/scrollers \
TouchGFX_App/touchgfx/framework/source/touchgfx/widgets \
TouchGFX_App/touchgfx/framework/source/touchgfx/widgets/canvas \
TouchGFX_App/touchgfx/framework/source/touchgfx/widgets/graph \
USB_DEVICE/App \
USB_DEVICE/Target \

